name: Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Firebase CLI
        run: npm install -g firebase-tools
        working-directory: ./backend

      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      - name: Run build
        run: npm run build
        working-directory: ./backend

      - name: Deploy to Firebase
        run: npm run deploy
        working-directory: ./backend
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
